version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    #image: username/repo:tag
    image: idthusitha/get-started:part2
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 10M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
