---
- hosts: webservers
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars:
    root_location: "/demosystem/"
    user_name: "ubuntu"
    copy_soft_file: true    
    copy_java: false
    
    tomcat_version: "apache-tomcat-8.0.36"
    java_version: "jdk1.8.0_144"
    jdk_archive_file: "jdk1.8.0_144.tar.gz"
    
    nexus_server: "############"
    nexus_user_name: "############"
    nexus_password: "############"
    
    mysql_root_password: "123456"
    
    deploy_war_name: "aws-web.war"
  roles:
#    -  default
#    -  nginx
#    -  java
#    -  mysql
#    -  tomcat
#    -  deploy
     -  tomcat-restart